# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-25 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beeflow', '0005_flowrecord_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='in_queue',
            field=models.BooleanField(default=True, help_text='只要任务没被人处理，就会一直在queue中'),
        ),
    ]
