# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 06:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beeflow', '0009_auto_20170430_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowrecord',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '同意'), (1, '拒绝'), (2, '需额外审批人审批'), (3, '待处理')], verbose_name='审批状态'),
        ),
        migrations.AlterField(
            model_name='flowrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审批用户'),
        ),
    ]
