# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-21 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_auto_20170328_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_customers', '可以访问 客户库'), ('crm_table_list', '可以访问 kingadmin 每个表的数据列表页'), ('crm_table_index', '可以访问 kingadmin 首页'), ('crm_table_list_view', '可以访问 kingadmin 每个表中对象的修改页'), ('crm_table_list_change', '可以修改 kingadmin 每个表中对象'), ('crm_table_list_action', '可以操作 每个表的 action 功能'), ('crm_can_access_my_clients', '可以访问 自己的 客户列表')), 'verbose_name': 'CRM账户', 'verbose_name_plural': 'CRM账户'},
        ),
    ]
